### ISSUE TITLE
odsclient unit tests fail from time to time because a dataset is changed/removed from the public ODS site

### ISSUE THREAD

**Issue by smarie** [opendatasoft/ods-documentation#268]
@ahervy or others: it is the second time in the past months that the unit tests in [`odsclient`]() fail because a dataset disappeared from the public ODS.

https://github.com/smarie/python-odsclient/issues/22
https://github.com/smarie/python-odsclient/issues/23

Just so you know: I now will use the following dataset as reference: https://public.opendatasoft.com/explore/dataset/respect-des-delais-dacheminement-courrier/export/

Can you kindly make sure that it does not go away ? :)
Thanks very much !

**Comment by thoumasd** [comment]
Answered here: https://github.com/smarie/python-odsclient/issues/23#issuecomment-758542036
